import { useEffect, useState } from 'react'
import { adminService, orderService } from '../services/services'

export default function Admin() {
	const [data, setData] = useState({ users: [], photographers: [], photos: [], products: [], orders: [] })
	const [error, setError] = useState('')
	useEffect(() => { Promise.all([adminService.users(), adminService.photographers(), adminService.photos(), adminService.products(), adminService.orders()]).then(([users, photographers, photos, products, orders]) => setData({ users: users.data, photographers: photographers.data, photos: photos.data, products: products.data, orders: orders.data })).catch((err) => setError(err.userMessage || 'Could not load the administrator dashboard.')) }, [])
	async function updateStatus(order) { const next = window.prompt(`New status for order #${order.id}`, order.status); if (!next || next === order.status) return; try { const { data: updated } = await orderService.updateStatus(order.id, next.toUpperCase()); setData((current) => ({ ...current, orders: current.orders.map((item) => item.id === order.id ? updated : item) })) } catch (err) { setError(err.userMessage || 'That status transition is not allowed.') } }
	return <main className="page-shell"><p className="eyebrow">Administrator dashboard</p><h2>Platform overview.</h2>{error && <div className="alert">{error}</div>}<div className="grid">{[['Users', data.users.length], ['Photographers', data.photographers.length], ['Photos', data.photos.length], ['Products', data.products.length], ['Orders', data.orders.length]].map(([label, count]) => <article className="photo-card" style={{ minHeight: 150 }} key={label}><div className="photo-card-body"><p className="eyebrow">{label}</p><h3>{count}</h3></div></article>)}</div><h2 style={{ marginTop: 64 }}>Orders</h2><div className="table-wrap"><table><thead><tr><th>Order</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>{data.orders.map((order) => <tr key={order.id}><td>#{order.id}</td><td>{order.status}</td><td>${order.total_amount}</td><td><button className="link-button" onClick={() => updateStatus(order)}>Change status</button></td></tr>)}</tbody></table></div></main>
}
